<?php

declare(strict_types=1);

namespace App\Enums;

use Filament\Support\Contracts\HasLabel;

enum CountryCode: string implements HasLabel
{
    // EU tagállamok
    case AT = 'AT'; // Ausztria
    case BE = 'BE'; // Belgium
    case BG = 'BG'; // Bulgária
    case CY = 'CY'; // Ciprus
    case CZ = 'CZ'; // Csehország
    case DK = 'DK'; // Dánia
    case EE = 'EE'; // Észtország
    case FI = 'FI'; // Finnország
    case FR = 'FR'; // Franciaország
    case GR = 'GR'; // Görögország
    case NL = 'NL'; // Hollandia
    case HR = 'HR'; // Horvátország
    case IE = 'IE'; // Írország
    case PL = 'PL'; // Lengyelország
    case LV = 'LV'; // Lettország
    case LT = 'LT'; // Litvánia
    case LU = 'LU'; // Luxemburg
    case MT = 'MT'; // Málta
    case DE = 'DE'; // Németország
    case IT = 'IT'; // Olaszország
    case PT = 'PT'; // Portugália
    case RO = 'RO'; // Románia
    case ES = 'ES'; // Spanyolország
    case SE = 'SE'; // Svédország
    case SK = 'SK'; // Szlovákia
    case SI = 'SI'; // Szlovénia
    case HU = 'HU'; // Magyarország

    // Speciális terület
    case XI = 'XI'; // Egyesült Királyság (Észak-Írország)

    // EU-n kívüli országok
    case AF = 'AF'; // Afganisztán
    case AL = 'AL'; // Albánia
    case DZ = 'DZ'; // Algéria
    case US = 'US'; // Amerikai Egyesült Államok
    case UM = 'UM'; // Amerikai Egyesült Államok Külső Szigetei
    case AS = 'AS'; // Amerikai Szamoa
    case AD = 'AD'; // Andorra
    case AO = 'AO'; // Angola
    case AI = 'AI'; // Anguilla
    case AQ = 'AQ'; // Antarktisz
    case AG = 'AG'; // Antigua és Barbuda
    case AR = 'AR'; // Argentína
    case AW = 'AW'; // Aruba
    case AU = 'AU'; // Ausztrália
    case AZ = 'AZ'; // Azerbajdzsán
    case BS = 'BS'; // Bahama-szigetek
    case BH = 'BH'; // Bahrein
    case BD = 'BD'; // Banglades
    case BB = 'BB'; // Barbados
    case BY = 'BY'; // Fehéroroszország
    case BZ = 'BZ'; // Belize
    case BJ = 'BJ'; // Benin
    case BM = 'BM'; // Bermuda
    case BT = 'BT'; // Bhután
    case GW = 'GW'; // Bissau-Guinea
    case BO = 'BO'; // Bolívia
    case BQ = 'BQ'; // Bonaire, Sint Eustatius és Saba
    case BA = 'BA'; // Bosznia-Hercegovina
    case BW = 'BW'; // Botswana
    case BV = 'BV'; // Bouvet-sziget
    case BR = 'BR'; // Brazília
    case IO = 'IO'; // Brit Indiai-óceáni Terület
    case BN = 'BN'; // Brunei
    case BF = 'BF'; // Burkina Faso
    case BI = 'BI'; // Burundi
    case XC = 'XC'; // Ceuta
    case CL = 'CL'; // Chile
    case KM = 'KM'; // Comore-szigetek
    case CK = 'CK'; // Cook-szigetek
    case CR = 'CR'; // Costa Rica
    case TD = 'TD'; // Csád
    case CW = 'CW'; // Curacao
    case ZA = 'ZA'; // Dél-Afrika
    case GS = 'GS'; // Dél-Georgia és a Déli-Sandwich-szigetek
    case SS = 'SS'; // Dél-Szudán
    case DM = 'DM'; // Dominika
    case DO = 'DO'; // Dominikai Köztársaság
    case DJ = 'DJ'; // Dzsibuti
    case EC = 'EC'; // Ecuador
    case GQ = 'GQ'; // Egyenlítői-Guinea
    case AE = 'AE'; // Egyesült Arab Emírségek
    case XU = 'XU'; // Egyesült Királyság (Észak-Írország nélkül)
    case EG = 'EG'; // Egyiptom
    case CI = 'CI'; // Elefántcsontpart
    case ER = 'ER'; // Eritrea
    case MP = 'MP'; // Északi-Mariana-Szigetek
    case ET = 'ET'; // Etiópia
    case FK = 'FK'; // Falkland-szigetek
    case FO = 'FO'; // Feröer-szigetek
    case FJ = 'FJ'; // Fidzsi-szigetek
    case TF = 'TF'; // Francia Déli Területek
    case PF = 'PF'; // Francia Polinézia
    case PH = 'PH'; // Fülöp-szigetek
    case GA = 'GA'; // Gabon
    case GM = 'GM'; // Gambia
    case GH = 'GH'; // Ghána
    case GI = 'GI'; // Gibraltár
    case GD = 'GD'; // Grenada
    case GL = 'GL'; // Grönland
    case GE = 'GE'; // Grúzia
    case GU = 'GU'; // Guam
    case GT = 'GT'; // Guatemala
    case GN = 'GN'; // Guinea
    case GY = 'GY'; // Guyana
    case HT = 'HT'; // Haiti
    case HM = 'HM'; // Heard-sziget és McDonald-szigetek
    case HN = 'HN'; // Honduras
    case HK = 'HK'; // Hongkong
    case IN = 'IN'; // India
    case ID = 'ID'; // Indonézia
    case IQ = 'IQ'; // Irak
    case IR = 'IR'; // Iráni Iszlám Köztársaság
    case IS = 'IS'; // Izland
    case IL = 'IL'; // Izrael
    case JM = 'JM'; // Jamaica
    case JP = 'JP'; // Japán
    case YE = 'YE'; // Jemen
    case JO = 'JO'; // Jordánia
    case KY = 'KY'; // Kajmán-szigetek
    case KH = 'KH'; // Kambodzsa
    case CM = 'CM'; // Kamerun
    case CA = 'CA'; // Kanada
    case CX = 'CX'; // Karácsony-sziget
    case QA = 'QA'; // Katar
    case KZ = 'KZ'; // Kazahsztán
    case TL = 'TL'; // Kelet-Timor
    case KE = 'KE'; // Kenya
    case CN = 'CN'; // Kína
    case KG = 'KG'; // Kirgiz Köztársaság
    case KI = 'KI'; // Kiribati
    case CC = 'CC'; // Kókusz-szigetek
    case CO = 'CO'; // Kolumbia
    case CG = 'CG'; // Kongó
    case CD = 'CD'; // Kongói Demokratikus Köztársaság
    case KR = 'KR'; // Koreai Köztársaság (Dél-Korea)
    case KP = 'KP'; // Koreai Népi Demokratikus Köztársaság (Észak-Korea)
    case XK = 'XK'; // Koszovó
    case CF = 'CF'; // Közép-afrikai Köztársaság
    case CU = 'CU'; // Kuba
    case KW = 'KW'; // Kuvait
    case LA = 'LA'; // Laoszi Népi Demokratikus Köztársaság
    case LS = 'LS'; // Lesotho
    case LB = 'LB'; // Libanon
    case LR = 'LR'; // Libéria
    case LY = 'LY'; // Líbia
    case LI = 'LI'; // Liechtenstein
    case MK = 'MK'; // Észak-Macedónia
    case MG = 'MG'; // Madagaszkár
    case MO = 'MO'; // Makaó
    case MY = 'MY'; // Malajzia
    case MW = 'MW'; // Malawi
    case MV = 'MV'; // Maldív-szigetek
    case ML = 'ML'; // Mali
    case MA = 'MA'; // Marokkó
    case MH = 'MH'; // Marshall-szigetek
    case MR = 'MR'; // Mauritánia
    case MU = 'MU'; // Mauritius
    case XL = 'XL'; // Melilla
    case MX = 'MX'; // Mexikó
    case MM = 'MM'; // Mianmar (Burma)
    case FM = 'FM'; // Mikronéziai Szövetségi Államok
    case MD = 'MD'; // Moldova
    case MN = 'MN'; // Mongólia
    case ME = 'ME'; // Montenegró
    case MS = 'MS'; // Montserrat
    case MZ = 'MZ'; // Mozambik
    case NA = 'NA'; // Namíbia
    case NR = 'NR'; // Nauru
    case NP = 'NP'; // Nepál
    case NI = 'NI'; // Nicaragua
    case NE = 'NE'; // Niger
    case NG = 'NG'; // Nigéria
    case NU = 'NU'; // Niue
    case NF = 'NF'; // Norfolk-sziget
    case NO = 'NO'; // Norvégia
    case EH = 'EH'; // Nyugat-Szahara
    case OM = 'OM'; // Omán
    case AM = 'AM'; // Örményország
    case RU = 'RU'; // Orosz Föderáció (Oroszország)
    case PK = 'PK'; // Pakisztán
    case PW = 'PW'; // Palau
    case PS = 'PS'; // Megszállt palesztin területek
    case PA = 'PA'; // Panama
    case PG = 'PG'; // Pápua Új-Giunea
    case PY = 'PY'; // Paraguay
    case PE = 'PE'; // Peru
    case PN = 'PN'; // Pitcairn-szigetek
    case RW = 'RW'; // Ruanda
    case BL = 'BL'; // Saint-Barthélémy
    case KN = 'KN'; // Saint Kitts és Nevis
    case LC = 'LC'; // Saint Lucia
    case SX = 'SX'; // Saint-Martin
    case PM = 'PM'; // Saint Pierre és Miquelon
    case VC = 'VC'; // Saint Vincent és Grenadine-szigetek
    case SB = 'SB'; // Salamon-szigetek
    case SV = 'SV'; // Salvador
    case SM = 'SM'; // San Marino
    case ST = 'ST'; // Sao Tomé és Príncipe
    case SC = 'SC'; // Seychelle-szigetek
    case SL = 'SL'; // Sierra Leone
    case LK = 'LK'; // Srí Lanka
    case SR = 'SR'; // Suriname
    case CH = 'CH'; // Svájc
    case WS = 'WS'; // Szamoa
    case SA = 'SA'; // Szaúd-Arábia
    case SN = 'SN'; // Szenegál
    case SH = 'SH'; // Szent Ilona, Ascension-sziget, Tristan da Cunha
    case XS = 'XS'; // Szerbia
    case SG = 'SG'; // Szingapúr
    case SY = 'SY'; // Szíriai Arab Köztársaság
    case SO = 'SO'; // Szomália
    case SD = 'SD'; // Szudán
    case SZ = 'SZ'; // Szváziföld
    case TJ = 'TJ'; // Tádzsikisztán
    case TW = 'TW'; // Tajvan
    case TZ = 'TZ'; // Tanzániai Egyesült Köztársaság
    case TH = 'TH'; // Thaiföld
    case TG = 'TG'; // Togo
    case TK = 'TK'; // Tokelau-szigetek
    case TO = 'TO'; // Tonga
    case TR = 'TR'; // Törökország
    case TT = 'TT'; // Trinidad és Tobago
    case TN = 'TN'; // Tunézia
    case TM = 'TM'; // Türkmenisztán
    case TC = 'TC'; // Turks- és Caicos-szigetek
    case TV = 'TV'; // Tuvalu
    case UG = 'UG'; // Uganda
    case NC = 'NC'; // Új-Kaledónia
    case NZ = 'NZ'; // Új-Zéland
    case UA = 'UA'; // Ukrajna
    case UY = 'UY'; // Uruguay
    case UZ = 'UZ'; // Üzbegisztán
    case VU = 'VU'; // Vanuatu
    case VA = 'VA'; // Vatikán (Apostoli Szentszék)
    case VE = 'VE'; // Venezuela
    case VN = 'VN'; // Vietnam
    case VI = 'VI'; // Virgin-szigetek (amerikai)
    case VG = 'VG'; // Virgin-szigetek (brit)
    case WF = 'WF'; // Wallis- és Futuna-szigetek
    case ZM = 'ZM'; // Zambia
    case ZW = 'ZW'; // Zimbabwe
    case CV = 'CV'; // Zöld-foki-szigetek

    public static function euMembers(): array
    {
        return array_filter(self::cases(), fn ($country) => $country->isEuMember());
    }

    public function getLabel(): string
    {
        return match ($this) {
            // EU tagállamok
            self::AT => 'Ausztria',
            self::BE => 'Belgium',
            self::BG => 'Bulgária',
            self::CY => 'Ciprus',
            self::CZ => 'Csehország',
            self::DK => 'Dánia',
            self::EE => 'Észtország',
            self::FI => 'Finnország',
            self::FR => 'Franciaország',
            self::GR => 'Görögország',
            self::NL => 'Hollandia',
            self::HR => 'Horvátország',
            self::IE => 'Írország',
            self::PL => 'Lengyelország',
            self::LV => 'Lettország',
            self::LT => 'Litvánia',
            self::LU => 'Luxemburg',
            self::MT => 'Málta',
            self::DE => 'Németország',
            self::IT => 'Olaszország',
            self::PT => 'Portugália',
            self::RO => 'Románia',
            self::ES => 'Spanyolország',
            self::SE => 'Svédország',
            self::SK => 'Szlovákia',
            self::SI => 'Szlovénia',
            self::HU => 'Magyarország',
            // Speciális terület
            self::XI => 'Egyesült Királyság (Észak-Írország)',
            // EU-n kívüli országok
            self::AF => 'Afganisztán',
            self::AL => 'Albánia',
            self::DZ => 'Algéria',
            self::US => 'Amerikai Egyesült Államok',
            self::UM => 'Amerikai Egyesült Államok Külső Szigetei',
            self::AS => 'Amerikai Szamoa',
            self::AD => 'Andorra',
            self::AO => 'Angola',
            self::AI => 'Anguilla',
            self::AQ => 'Antarktisz',
            self::AG => 'Antigua és Barbuda',
            self::AR => 'Argentína',
            self::AW => 'Aruba',
            self::AU => 'Ausztrália',
            self::AZ => 'Azerbajdzsán',
            self::BS => 'Bahama-szigetek',
            self::BH => 'Bahrein',
            self::BD => 'Banglades',
            self::BB => 'Barbados',
            self::BY => 'Fehéroroszország',
            self::BZ => 'Belize',
            self::BJ => 'Benin',
            self::BM => 'Bermuda',
            self::BT => 'Bhután',
            self::GW => 'Bissau-Guinea',
            self::BO => 'Bolívia',
            self::BQ => 'Bonaire, Sint Eustatius és Saba',
            self::BA => 'Bosznia-Hercegovina',
            self::BW => 'Botswana',
            self::BV => 'Bouvet-sziget',
            self::BR => 'Brazília',
            self::IO => 'Brit Indiai-óceáni Terület',
            self::BN => 'Brunei',
            self::BF => 'Burkina Faso',
            self::BI => 'Burundi',
            self::XC => 'Ceuta',
            self::CL => 'Chile',
            self::KM => 'Comore-szigetek',
            self::CK => 'Cook-szigetek',
            self::CR => 'Costa Rica',
            self::TD => 'Csád',
            self::CW => 'Curacao',
            self::ZA => 'Dél-Afrika',
            self::GS => 'Dél-Georgia és a Déli-Sandwich-szigetek',
            self::SS => 'Dél-Szudán',
            self::DM => 'Dominika',
            self::DO => 'Dominikai Köztársaság',
            self::DJ => 'Dzsibuti',
            self::EC => 'Ecuador',
            self::GQ => 'Egyenlítői-Guinea',
            self::AE => 'Egyesült Arab Emírségek',
            self::XU => 'Egyesült Királyság (Észak-Írország nélkül)',
            self::EG => 'Egyiptom',
            self::CI => 'Elefántcsontpart',
            self::ER => 'Eritrea',
            self::MP => 'Északi-Mariana-Szigetek',
            self::ET => 'Etiópia',
            self::FK => 'Falkland-szigetek',
            self::FO => 'Feröer-szigetek',
            self::FJ => 'Fidzsi-szigetek',
            self::TF => 'Francia Déli Területek',
            self::PF => 'Francia Polinézia',
            self::PH => 'Fülöp-szigetek',
            self::GA => 'Gabon',
            self::GM => 'Gambia',
            self::GH => 'Ghána',
            self::GI => 'Gibraltár',
            self::GD => 'Grenada',
            self::GL => 'Grönland',
            self::GE => 'Grúzia',
            self::GU => 'Guam',
            self::GT => 'Guatemala',
            self::GN => 'Guinea',
            self::GY => 'Guyana',
            self::HT => 'Haiti',
            self::HM => 'Heard-sziget és McDonald-szigetek',
            self::HN => 'Honduras',
            self::HK => 'Hongkong',
            self::IN => 'India',
            self::ID => 'Indonézia',
            self::IQ => 'Irak',
            self::IR => 'Iráni Iszlám Köztársaság',
            self::IS => 'Izland',
            self::IL => 'Izrael',
            self::JM => 'Jamaica',
            self::JP => 'Japán',
            self::YE => 'Jemen',
            self::JO => 'Jordánia',
            self::KY => 'Kajmán-szigetek',
            self::KH => 'Kambodzsa',
            self::CM => 'Kamerun',
            self::CA => 'Kanada',
            self::CX => 'Karácsony-sziget',
            self::QA => 'Katar',
            self::KZ => 'Kazahsztán',
            self::TL => 'Kelet-Timor',
            self::KE => 'Kenya',
            self::CN => 'Kína',
            self::KG => 'Kirgiz Köztársaság',
            self::KI => 'Kiribati',
            self::CC => 'Kókusz-szigetek',
            self::CO => 'Kolumbia',
            self::CG => 'Kongó',
            self::CD => 'Kongói Demokratikus Köztársaság',
            self::KR => 'Koreai Köztársaság (Dél-Korea)',
            self::KP => 'Koreai Népi Demokratikus Köztársaság (Észak-Korea)',
            self::XK => 'Koszovó',
            self::CF => 'Közép-afrikai Köztársaság',
            self::CU => 'Kuba',
            self::KW => 'Kuvait',
            self::LA => 'Laoszi Népi Demokratikus Köztársaság',
            self::LS => 'Lesotho',
            self::LB => 'Libanon',
            self::LR => 'Libéria',
            self::LY => 'Líbia',
            self::LI => 'Liechtenstein',
            self::MK => 'Észak-Macedónia',
            self::MG => 'Madagaszkár',
            self::MO => 'Makaó',
            self::MY => 'Malajzia',
            self::MW => 'Malawi',
            self::MV => 'Maldív-szigetek',
            self::ML => 'Mali',
            self::MA => 'Marokkó',
            self::MH => 'Marshall-szigetek',
            self::MR => 'Mauritánia',
            self::MU => 'Mauritius',
            self::XL => 'Melilla',
            self::MX => 'Mexikó',
            self::MM => 'Mianmar (Burma)',
            self::FM => 'Mikronéziai Szövetségi Államok',
            self::MD => 'Moldova',
            self::MN => 'Mongólia',
            self::ME => 'Montenegró',
            self::MS => 'Montserrat',
            self::MZ => 'Mozambik',
            self::NA => 'Namíbia',
            self::NR => 'Nauru',
            self::NP => 'Nepál',
            self::NI => 'Nicaragua',
            self::NE => 'Niger',
            self::NG => 'Nigéria',
            self::NU => 'Niue',
            self::NF => 'Norfolk-sziget',
            self::NO => 'Norvégia',
            self::EH => 'Nyugat-Szahara',
            self::OM => 'Omán',
            self::AM => 'Örményország',
            self::RU => 'Orosz Föderáció (Oroszország)',
            self::PK => 'Pakisztán',
            self::PW => 'Palau',
            self::PS => 'Megszállt palesztin területek',
            self::PA => 'Panama',
            self::PG => 'Pápua Új-Giunea',
            self::PY => 'Paraguay',
            self::PE => 'Peru',
            self::PN => 'Pitcairn-szigetek',
            self::RW => 'Ruanda',
            self::BL => 'Saint-Barthélémy',
            self::KN => 'Saint Kitts és Nevis',
            self::LC => 'Saint Lucia',
            self::SX => 'Saint-Martin',
            self::PM => 'Saint Pierre és Miquelon',
            self::VC => 'Saint Vincent és Grenadine-szigetek',
            self::SB => 'Salamon-szigetek',
            self::SV => 'Salvador',
            self::SM => 'San Marino',
            self::ST => 'Sao Tomé és Príncipe',
            self::SC => 'Seychelle-szigetek',
            self::SL => 'Sierra Leone',
            self::LK => 'Srí Lanka',
            self::SR => 'Suriname',
            self::CH => 'Svájc',
            self::WS => 'Szamoa',
            self::SA => 'Szaúd-Arábia',
            self::SN => 'Szenegál',
            self::SH => 'Szent Ilona, Ascension-sziget, Tristan da Cunha',
            self::XS => 'Szerbia',
            self::SG => 'Szingapúr',
            self::SY => 'Szíriai Arab Köztársaság',
            self::SO => 'Szomália',
            self::SD => 'Szudán',
            self::SZ => 'Szváziföld',
            self::TJ => 'Tádzsikisztán',
            self::TW => 'Tajvan',
            self::TZ => 'Tanzániai Egyesült Köztársaság',
            self::TH => 'Thaiföld',
            self::TG => 'Togo',
            self::TK => 'Tokelau-szigetek',
            self::TO => 'Tonga',
            self::TR => 'Törökország',
            self::TT => 'Trinidad és Tobago',
            self::TN => 'Tunézia',
            self::TM => 'Türkmenisztán',
            self::TC => 'Turks- és Caicos-szigetek',
            self::TV => 'Tuvalu',
            self::UG => 'Uganda',
            self::NC => 'Új-Kaledónia',
            self::NZ => 'Új-Zéland',
            self::UA => 'Ukrajna',
            self::UY => 'Uruguay',
            self::UZ => 'Üzbegisztán',
            self::VU => 'Vanuatu',
            self::VA => 'Vatikán (Apostoli Szentszék)',
            self::VE => 'Venezuela',
            self::VN => 'Vietnam',
            self::VI => 'Virgin-szigetek (amerikai)',
            self::VG => 'Virgin-szigetek (brit)',
            self::WF => 'Wallis- és Futuna-szigetek',
            self::ZM => 'Zambia',
            self::ZW => 'Zimbabwe',
            self::CV => 'Zöld-foki-szigetek',
        };
    }

    public function isEuMember(): bool
    {
        return match ($this) {
            self::AT, self::BE, self::BG, self::CY, self::CZ, self::DK,
            self::EE, self::FI, self::FR, self::GR, self::NL, self::HR,
            self::IE, self::PL, self::LV, self::LT, self::LU, self::MT,
            self::DE, self::IT, self::PT, self::RO, self::ES, self::SE,
            self::SK, self::SI, self::HU => true,
            self::XI => false, // Észak-Írország speciális státusz
            default => false,
        };
    }
}
